version: '3'

services:
  # PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  # Django app service
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  # Celery worker service
  celery:
    build: .
    command: celery -A catalyst_count worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
