# Generated by Django 5.1.3 on 2024-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("size_range", models.CharField(blank=True, max_length=100, null=True)),
                ("locality", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "current_employee_estimate",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_employee_estimate", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
