# Generated by Django 5.1.3 on 2024-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_companydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvrecord",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
